name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v2
     # with:
      #terraform_version: 1.3.6
    - name: Deploy on Production
      run: |
        cd deploy/ && terraform init
        cd deploy/ && terraform validate
       # cd deploy/ && terraform apply -auto-approve
       # cd deploy/ && git commit -m 'store terraform state file'
       # cd deploy/ && git push

