name: 'Terraform GitHub Actions'
on:
  - push
jobs:
  root:
    name: 'Terraform (root)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
      - name: 'Terraform validate'
        run: terraform validate

      
         
         
         
     # cd deploy/ && terraform apply -auto-approve
       # cd deploy/ && git commit -m 'store terraform state file'
       # cd deploy/ && git push

